sonar.projectKey=wagaodev_PlateGuard
sonar.organization=wagaodev
sonar.projectName=PlateGuard

sonar.sources=app-backend/src,app-mobile/src
sonar.tests=app-backend/test
sonar.typescript.lcov.reportPaths=app-backend/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/android/**,**/ios/**,**/*.spec.ts,**/generated/**
sonar.test.inclusions=**/*.spec.ts,**/*.e2e.spec.ts

sonar.sourceEncoding=UTF-8
